### ISSUE TITLE
import "utils" could not be resolved Pylance

### ISSUE THREAD

**Issue by prajwalarista** [aristanetworks/cloudvision-python#4]
The scripts such as "get_intf_rate.py" in the connector directory are showing this problem and not able to execute the script. Wherever there is "from utils import", is is throwing this error.

**Comment by cianmcgrath** [comment]
This is a purely cosmetic issue in terms of functionality. The import does work, it just does not offer any autocomplete options as the pylance path cannot find `utils` with the paths it has. 
_You will still be able to execute the script._ 
The examples folder was written as an independent module which is what is what is causing this issue. (https://github.com/microsoft/pylance-release/issues/236 is pretty much exactly what is happening here and gives some background if you're interested)
Changing the import to be relative from the root of the repository (changing utils to examples.Connector.utils) solves this cosmetic issue but actually breaks the importing itself. To solve the issue permanently you need to add examples/Connector to the Extra Paths for pylance. (I've attached a screenshot of doing it in the settings for VSCode)
Hope that helps
![image](https://user-images.githubusercontent.com/63802852/142246297-1af7e083-a7d3-4cf4-a2b3-6e3996fbf703.png)
